<a href="https://www.kaggle.com/code/swish9/air-quality?scriptVersionId=119706615" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/airquality/AirQualityUCI.csv


In [2]:
import matplotlib.pyplot as plt
dataset = pd.read_csv('/kaggle/input/airquality/AirQualityUCI.csv')

In [3]:
dataset

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0     10/3/2004  18.00.00     2.6         1360     150.0      11.9   
1     10/3/2004  19.00.00     2.0         1292     112.0       9.4   
2     10/3/2004  20.00.00     2.2         1402      88.0       9.0   
3     10/3/2004  21.00.00     2.2         1376      80.0       9.2   
4     10/3/2004  22.00.00     1.6         1272      51.0       6.5   
...         ...       ...     ...          ...       ...       ...   
9352   4/4/2005  10.00.00     3.1         1314    -200.0      13.5   
9353   4/4/2005  11.00.00     2.4         1163    -200.0      11.4   
9354   4/4/2005  12.00.00     2.4         1142    -200.0      12.4   
9355   4/4/2005  13.00.00     2.1         1003    -200.0       9.5   
9356   4/4/2005  14.00.00     2.2         1071    -200.0      11.9   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0              1046      166          1056      113          1692   
1               955      103          1174       92          1559   
2               939      131          1140      114          1555   
3               948      172          1092      122          1584   
4               836      131          1205      116          1490   
...             ...      ...           ...      ...           ...   
9352           1101      472           539      190          1374   
9353           1027      353           604      179          1264   
9354           1063      293           603      175          1241   
9355            961      235           702      156          1041   
9356           1047      265           654      168          1129   

      PT08.S5(O3)     T    RH      AH  
0          1268.0  13.6  48.9  0.7578  
1           972.0  13.3  47.7  0.7255  
2          1074.0  11.9  54.0  0.7502  
3          1203.0  11.0  60.0  0.7867  
4          1110.0  11.2  59.6  0.7888  
...           ...   ...   ...     ...  
9352       1729.0  21.9  29.3  0.7568  
9353       1269.0  24.3  23.7  0.7119  
9354       1092.0  26.9  18.3  0.6406  
9355        770.0  28.3  13.5  0.5139  
9356        816.0  28.5  13.1  0.5028  

[9357 rows x 15 columns]

In [4]:
dataset.head(5)

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  10/3/2004  18.00.00     2.6         1360     150.0      11.9   
1  10/3/2004  19.00.00     2.0         1292     112.0       9.4   
2  10/3/2004  20.00.00     2.2         1402      88.0       9.0   
3  10/3/2004  21.00.00     2.2         1376      80.0       9.2   
4  10/3/2004  22.00.00     1.6         1272      51.0       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0           1046      166          1056      113          1692       1268.0   
1            955      103          1174       92          1559        972.0   
2            939      131          1140      114          1555       1074.0   
3            948      172          1092      122          1584       1203.0   
4            836      131          1205      116          1490       1110.0   

      T    RH      AH  
0  13.6  48.9  0.7578  
1  13.3  47.7  0.7255  
2  11.9  54.0  0.7502  
3  11.0  60.0  0.7867  
4  11.2  59.6  0.7888

In [5]:
dataset.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               1
dtype: int64

In [6]:
dataset['AH']

0       0.7578
1       0.7255
2       0.7502
3       0.7867
4       0.7888
         ...  
9352    0.7568
9353    0.7119
9354    0.6406
9355    0.5139
9356    0.5028
Name: AH, Length: 9357, dtype: float64

In [7]:
dataset['AH'].mean()

-6.838464290294997

In [8]:
dataset['AH'].median()

0.9768

In [9]:
dataset['AH'].fillna(value = dataset['AH'].mean(),inplace=True)

In [10]:
dataset.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         0
C6H6(GT)         0
PT08.S2(NMHC)    0
NOx(GT)          0
PT08.S3(NOx)     0
NO2(GT)          0
PT08.S4(NO2)     0
PT08.S5(O3)      0
T                0
RH               0
AH               0
dtype: int64

In [11]:
#reduce columns
dataset = dataset.drop('Date', axis=1)
dataset = dataset.drop('Time', axis=1)
dataset = dataset.drop('C6H6(GT)', axis=1)

In [12]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [13]:
print(x)

y

[[   2.6 1360.   150.  ... 1268.    13.6   48.9]
 [   2.  1292.   112.  ...  972.    13.3   47.7]
 [   2.2 1402.    88.  ... 1074.    11.9   54. ]
 ...
 [   2.4 1142.  -200.  ... 1092.    26.9   18.3]
 [   2.1 1003.  -200.  ...  770.    28.3   13.5]
 [   2.2 1071.  -200.  ...  816.    28.5   13.1]]


array([0.7578, 0.7255, 0.7502, ..., 0.6406, 0.5139, 0.5028])

In [14]:
dataset.head()

CO(GT)  PT08.S1(CO)  NMHC(GT)  PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  \
0     2.6         1360     150.0           1046      166          1056   
1     2.0         1292     112.0            955      103          1174   
2     2.2         1402      88.0            939      131          1140   
3     2.2         1376      80.0            948      172          1092   
4     1.6         1272      51.0            836      131          1205   

   NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH      AH  
0      113          1692       1268.0  13.6  48.9  0.7578  
1       92          1559        972.0  13.3  47.7  0.7255  
2      114          1555       1074.0  11.9  54.0  0.7502  
3      122          1584       1203.0  11.0  60.0  0.7867  
4      116          1490       1110.0  11.2  59.6  0.7888

typecasting all values into into ( I'm not sure if this is the best method to do so).

In [15]:
dataset = dataset.applymap(int)

Spliting dataset into x and y

In [16]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [17]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')


In [18]:
regressor.fit(X, y)

SVR()

In [19]:
r_sq = regressor.score(X, y)
r_sq

0.9979738146948102

DAMN,Thanks dude kNi.
This is the best model which I've trained untill now.( i'm assuming score should be 1 for a model to be perfect 😅.)

 Split the data into training and testing sets


In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,  random_state =0)

In [21]:
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)


In [22]:
from sklearn.metrics import mean_squared_error, r2_score


Calculating performance accuracy


In [23]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [24]:
mse

2.709572236707783

In [25]:
r2

0.9981446765960214

# > **My final score is 0.9981446765960214**